version: "3.8"

networks:
  moscow-net:

services:
#  zookeeper:
#    image: zookeeper
#    container_name: zookeeper
#    volumes:
#      - ~/kafka/data/zookeeper_data:/var/lib/zookeeper/data
#      - ~/kafka/data/zookeeper_log:/var/lib/zookeeper/log
#    networks:
#      - moscow-net
#    ports:
#      - "2181:2181"
#    environment:
#      ZOOKEEPER_CLIENT_PORT: 2181
#      ZOOKEEPER_TICK_TIME: 2000

#  broker:
#    image: confluentinc/cp-kafka
#    container_name: broker
#    volumes:
#      - ./kafka-data:/kafka/kafka-logs
#    networks:
#      - moscow-net
#    ports:
#      - "9092:9092"
#    depends_on:
#      - zookeeper
#    environment:
#      KAFKA_BROKER_ID: 1
#      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
#      KAFKA_BROKER_LISTENER_NAME: PLAINTEXT
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
#      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  postgres:
    image: "postgres"
    networks:
      - moscow-net
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: S3cret
      POSTGRES_USER: user
      POSTGRES_DB: db

#  notifications:
#    build: ./notifications
#    networks:
#      - moscow-net
#    container_name: notifications
#    depends_on:
#      - broker
#    ports:
#      - "8090:8080"
#    environment:
#      SERVER_PORT: 8080
#      SPRING_PROFILES_ACTIVE: "dev"
#      APPLICATION_KAFKA_TOPIC: "notification.created"
#      SPRING_KAFKA_BOOTSTRAP_SERVERS: "broker:29092"
#      SPRING_KAFKA_CONSUMER_GROUP_ID: "applog"

  materials:
    build: ./materials
    networks:
      - moscow-net
    container_name: materials
    depends_on:
      - postgres
    ports:
      - "8091:8081"
    environment:
      SERVER_PORT: 8081
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: S3cret